---
name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Ruby ${{ matrix.ruby }}, ${{ matrix.gemfile }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - '3.0'
          - 3.1
          - head
        gemfile:
          - gemfiles/rails5.gemfile
          - gemfiles/rails6.0.gemfile
          - gemfiles/rails6.1.gemfile
          - gemfiles/rails7.0.gemfile
        exclude:
          - ruby: '3.0'
            gemfile: gemfiles/rails5.gemfile
          - ruby: 3.1
            gemfile: gemfiles/rails5.gemfile
          - ruby: 3.1
            gemfile: gemfiles/rails6.0.gemfile
          - ruby: head
            gemfile: gemfiles/rails5.gemfile
          - ruby: head
            gemfile: gemfiles/rails6.0.gemfile
        os:
          - ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake coverage
 
